/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package predicatevisualiser;

/**
 *
 * @author Tim
 */
public class PredicateVisualiser extends javax.swing.JFrame {

    /**
     * Creates new form PredicateVisualiser
     */
    public PredicateVisualiser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutDialog = new javax.swing.JDialog();
        closeButton = new javax.swing.JButton();
        aboutText = new javax.swing.JLabel();
        predicateCreationDialog = new javax.swing.JDialog();
        finishButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        createPredicateInstructionsLabel = new javax.swing.JLabel();
        namePanel = new javax.swing.JPanel();
        nameIcon = new ImagePanel("E:\\Users\\Tim\\Downloads\\glyphicons_free\\glyphicons_free\\glyphicons\\png\\glyphicons_351_book_open.png");
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        predicateNameIcon1 = new ImagePanel("E:\\Users\\Tim\\Downloads\\glyphicons_free\\glyphicons_free\\glyphicons\\png\\glyphicons_351_book_open.png");
        predicateNameLabel1 = new javax.swing.JLabel();
        nameTextField1 = new javax.swing.JTextField();
        mainViewLayeredPane = new javax.swing.JLayeredPane();
        predicateListViewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        predicateList = new javax.swing.JList();
        networkViewPanel = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newPredicateMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        predicateListMenuItem = new javax.swing.JMenuItem();
        networkMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        aboutDialog.setTitle("About Predicate Visualiser");
        aboutDialog.setAlwaysOnTop(true);
        aboutDialog.setMinimumSize(new java.awt.Dimension(300, 250));

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        aboutText.setText("<html>\n\n<style>\nh2 {\n\tmargin-top: 0;\n}\n\nul {\n\tmargin-left: 25pt;\n}\n</style>\n\n<h2 style=\"margin-top: 0;\">CS407 Group Project 2012</h2>\n\n<p>Authors:</p>\n<ul>\n\t<li>Matthew Bradbury</li>\n\t<li>Tim Law</li>\n\t<li>Ivan Leong</li>\n\t<li>Daniel Robertson</li>\n\t<li>Amit Shah</li>\n\t<li>Joseph Yarnall</li>\n</ul>");

        javax.swing.GroupLayout aboutDialogLayout = new javax.swing.GroupLayout(aboutDialog.getContentPane());
        aboutDialog.getContentPane().setLayout(aboutDialogLayout);
        aboutDialogLayout.setHorizontalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutDialogLayout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
            .addGroup(aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutDialogLayout.createSequentialGroup()
                    .addGap(0, 82, Short.MAX_VALUE)
                    .addComponent(aboutText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 82, Short.MAX_VALUE)))
        );
        aboutDialogLayout.setVerticalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutDialogLayout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
            .addGroup(aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutDialogLayout.createSequentialGroup()
                    .addGap(0, 75, Short.MAX_VALUE)
                    .addComponent(aboutText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 75, Short.MAX_VALUE)))
        );

        predicateCreationDialog.setTitle("Create New Predicate");
        predicateCreationDialog.setAlwaysOnTop(true);
        predicateCreationDialog.setMinimumSize(new java.awt.Dimension(357, 300));
        predicateCreationDialog.setResizable(false);

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        createPredicateInstructionsLabel.setText("<html>Fill out the fields below in order to create and monitor a new<br />predicate on the network.");

        javax.swing.GroupLayout nameIconLayout = new javax.swing.GroupLayout(nameIcon);
        nameIcon.setLayout(nameIconLayout);
        nameIconLayout.setHorizontalGroup(
            nameIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        nameIconLayout.setVerticalGroup(
            nameIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        nameLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        nameLabel.setText("Predicate Name: ");

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout predicateNameIcon1Layout = new javax.swing.GroupLayout(predicateNameIcon1);
        predicateNameIcon1.setLayout(predicateNameIcon1Layout);
        predicateNameIcon1Layout.setHorizontalGroup(
            predicateNameIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        predicateNameIcon1Layout.setVerticalGroup(
            predicateNameIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        predicateNameLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        predicateNameLabel1.setText("other things");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(predicateNameIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(predicateNameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(predicateNameLabel1)
                        .addComponent(nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(predicateNameIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout predicateCreationDialogLayout = new javax.swing.GroupLayout(predicateCreationDialog.getContentPane());
        predicateCreationDialog.getContentPane().setLayout(predicateCreationDialogLayout);
        predicateCreationDialogLayout.setHorizontalGroup(
            predicateCreationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(predicateCreationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(predicateCreationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(predicateCreationDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finishButton))
                    .addGroup(predicateCreationDialogLayout.createSequentialGroup()
                        .addGroup(predicateCreationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createPredicateInstructionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        predicateCreationDialogLayout.setVerticalGroup(
            predicateCreationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(predicateCreationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createPredicateInstructionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(predicateCreationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Predicate Visualiser");

        predicateListViewPanel.setBackground(new java.awt.Color(47, 255, 0));

        predicateList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(predicateList);

        javax.swing.GroupLayout predicateListViewPanelLayout = new javax.swing.GroupLayout(predicateListViewPanel);
        predicateListViewPanel.setLayout(predicateListViewPanelLayout);
        predicateListViewPanelLayout.setHorizontalGroup(
            predicateListViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(predicateListViewPanelLayout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        predicateListViewPanelLayout.setVerticalGroup(
            predicateListViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, predicateListViewPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        predicateListViewPanel.setBounds(20, 130, 760, 710);
        mainViewLayeredPane.add(predicateListViewPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        networkViewPanel.setBackground(new java.awt.Color(255, 128, 0));

        javax.swing.GroupLayout networkViewPanelLayout = new javax.swing.GroupLayout(networkViewPanel);
        networkViewPanel.setLayout(networkViewPanelLayout);
        networkViewPanelLayout.setHorizontalGroup(
            networkViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkViewPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        networkViewPanelLayout.setVerticalGroup(
            networkViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkViewPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        networkViewPanel.setBounds(120, 20, 380, 509);
        mainViewLayeredPane.add(networkViewPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fileMenu.setText("File");

        newPredicateMenuItem.setText("New Predicate");
        newPredicateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPredicateMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newPredicateMenuItem);

        quitMenuItem.setText("Quit");
        quitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(quitMenuItem);

        menuBar.add(fileMenu);

        viewMenu.setText("View");

        predicateListMenuItem.setText("Predicate List");
        predicateListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predicateListMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(predicateListMenuItem);

        networkMenuItem.setText("Network");
        networkMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(networkMenuItem);

        menuBar.add(viewMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainViewLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainViewLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        aboutDialog.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed
    
    private void quitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_quitMenuItemActionPerformed

    private void newPredicateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPredicateMenuItemActionPerformed
        predicateCreationDialog.setVisible(true);
    }//GEN-LAST:event_newPredicateMenuItemActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        //Validate
        //TODO
        if(true) {
            predicateCreationDialog.setVisible(false);
        }
        
        //Construct predicate object
        Predicate newPredicate = new Predicate();
        newPredicate.setName(nameTextField.getText());
        
        //Add predicate to list
        //javax.swing.DefaultListModel listModel = (javax.swing.DefaultListModel)predicateList.getModel();
        //listModel.addElement(newPredicate);
    }//GEN-LAST:event_finishButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        predicateCreationDialog.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void predicateListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predicateListMenuItemActionPerformed
        //Bring container panel to front.
        mainViewLayeredPane.setLayer(predicateListViewPanel, 0);
    }//GEN-LAST:event_predicateListMenuItemActionPerformed

    private void networkMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkMenuItemActionPerformed
        //Bring container panel to front.
        mainViewLayeredPane.setLayer(networkViewPanel, 0);
    }//GEN-LAST:event_networkMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Set the Windows look & feel
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PredicateVisualiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PredicateVisualiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PredicateVisualiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PredicateVisualiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PredicateVisualiser().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog aboutDialog;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel aboutText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel createPredicateInstructionsLabel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton finishButton;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLayeredPane mainViewLayeredPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel nameIcon;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nameTextField1;
    private javax.swing.JMenuItem networkMenuItem;
    private javax.swing.JPanel networkViewPanel;
    private javax.swing.JMenuItem newPredicateMenuItem;
    private javax.swing.JDialog predicateCreationDialog;
    private javax.swing.JList predicateList;
    private javax.swing.JMenuItem predicateListMenuItem;
    private javax.swing.JPanel predicateListViewPanel;
    private javax.swing.JPanel predicateNameIcon1;
    private javax.swing.JLabel predicateNameLabel1;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
