PROJECT_SOURCEFILES = $(CS407DIR)/Samples/Common/sensor-converter-broken.c $(CS407DIR)/Samples/Common/debug-helper.c predicate-checker.c

CONTIKI = $(HOME)/contiki-2.6
include $(CONTIKI)/Makefile.include
