CONTIKI_PROJECT = tree-aggregator
all: $(CONTIKI_PROJECT)

# Target references:
# http://www.sics.se/contiki/wiki/index.php/Contiki_make_targets

TARGET = sky

PROJECTDIRS = 
PROJECT_SOURCEFILES =

CONTIKIDIRS := $(CS407DIR)/Samples/Common
CONTIKI_SOURCEFILES = sensor-converter.c

CONTIKI = $(HOME)/contiki-2.6
include $(CONTIKI)/Makefile.include
